[bumpver]
current_version = "1.0.14"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"composer.json" = [
  '"version": "{version}",$',
]
"pow-captcha.php" = [
  "Version: {version}$",
  "define('POW_CAPTCHA_VERSION', '{version}');$",
]
"README.md" = [
  "Stable tag: {version}$",
]
"src/Widget.php" = [
  "'{version}'",
]
